name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # This will trigger the workflow when a tag matching v* is pushed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Only run the deployment job if a tag was pushed
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Ensure this matches the output folder
